spring:

  datasource:
    url:
      jdbc:sqlserver://database-server:1433;databaseName=shopal;
      integratedSecurity=false;
      encrypt=false;
      trustServerCertificate=true;
    username: ipension-operations
    password: P@ssw0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: false

  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
    host: smtp.gmail.com
    port: 587
    username: hoangtrungt373@gmail.com
    password: oxmbqtmbosuefoks
    default-encoding: UTF-8

server:
  port: 8095