drop table if exists staging.STAG_CUSTOMER;

CREATE TABLE staging.STAG_CUSTOMER
(
    STAG_CUSTOMER_ID      INT            NOT NULL IDENTITY,
    ID_CHECKING           INT            NOT NULL,
    FULL_NAME             NVARCHAR(255) NOT NULL,
    ENTERPRISE_ID         INT            NOT NULL,
    REGISTER_EMAIL        VARCHAR(255)   NOT NULL,
    INITIAL_POINT         DECIMAL(17, 2) NOT NULL,
    REGISTER_PHONE_NUMBER VARCHAR(255)   NOT NULL,
    IMPORT_DATE           DATETIME       NOT NULL,

    USR_LOG_I             VARCHAR(128)   NOT NULL,
    USR_LOG_U             VARCHAR(128)   NOT NULL,
    DATE_LOG_I            DATETIME2      NOT NULL,
    DATE_LOG_U            DATETIME2      NOT NULL,
    VERSION               INT            NOT NULL,

    CONSTRAINT PK_STAG_CUSTOMER PRIMARY KEY (STAG_CUSTOMER_ID)
)