create table shop.CUSTOMER_POINT_MOVEMENT
(
    CUSTOMER_POINT_MOVEMENT_ID INT IDENTITY,
    CUSTOMER_ID                INT          NOT NULL,
    PURCHASE_ORDER_ID          INT,
    DATE_MOVEMENT              DATETIME2    NOT NULL,
    TYPE_MOVEMENT              VARCHAR(20),
    VALUE                      DECIMAL(17, 2),
    PAY                        DECIMAL(17, 2),

    USR_LOG_I                  VARCHAR(128) NOT NULL,
    USR_LOG_U                  VARCHAR(128) NOT NULL,
    DATE_LOG_I                 DATETIME2    NOT NULL,
    DATE_LOG_U                 DATETIME2    NOT NULL,
    VERSION                    INT          NOT NULL,
    ID_ORIGIN                  INT          NOT NULL,

    CONSTRAINT PK_CUSTOMER_POINT_MOVEMENT PRIMARY KEY (CUSTOMER_POINT_MOVEMENT_ID),
    CONSTRAINT FK_CUSTOMER_POINT_MOVEMENT_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES shop.CUSTOMER (CUSTOMER_ID),
    CONSTRAINT FK_CUSTOMER_POINT_MOVEMENT_PURCHASE_ORDER FOREIGN KEY (PURCHASE_ORDER_ID) REFERENCES shop.PURCHASE_ORDER (PURCHASE_ORDER_ID)
)


